<s snum=25> angunasuktivut , inuqutivut ilitarijaulauqput pattatuqtaullutillu taimainginnarunnaqtumik aanninanngittumillu puijiniaqattanittinnut .  </s>
<s snum=26> pigiarnirmi gavamakkut turaagaqalauqput gavamakkut matuingaarniarmata piliriqatigiinniqattiarniarmatalu , tamatuminnga aaqqiinasukpugut maanna , angirutigilaurattigu pigiarningani .  </s>
<s snum=27> tamattinnit iqqaitittijumatuinnaqtunga piviqarniaratti tamakkuninnga isumaaluutittinnit apirijariaksaq katimajiralaakkunni tamainnut .  </s>
<s snum=28> ilitaqsimmijugut avittuqsimajut inuktituuliqtitautittijunnarningit tamainnik titirarnit maannaujut mikijuummat .  </s>
<s snum=29> uqaqtii , alianaigusujjualauqpunga pinasuarusiulauqtumi iglulingmut pularaqatigillugu maligaliuqti amitturmut .  </s>
<s snum=30> nunaliit tusaqsimavut annikitturvik sanajaunialirmat tavvani arraagumi , kisianili maanna ajjiginngitanganik tusaliqpugut .  </s>
<s snum=31> uqaqtii , qaujimatuinnauqquuratta upigusuttuinnauqquuqtutalu inungnit pijjutigillugu suuqaimma Haamalaujut uvagullu inungnut takakkunanngat niruaqtausimagatta .  </s>
<s snum=32> ii , mamianaq tamatuminnga apirilaurmanga ulluulisaaqtunit tammalauramalu kiunasuktugu .  </s>
<s snum=33> qujannamiirumammijungattauq nuliarnut miuriamut qiturnganullu marruliarnullu sallimiut aksuqjuaq matuingaaqsimammata ukiut 13nguliqtunit taikanimiutaunittinni .  </s>
<s snum=34> qaujigiarniaqpiit tamatuminnga isumaaluutimik arvilijjuarmik ammalu taikani pinnguarvingmik sanajaujuqarniarmangaaq arraaguttinni ?  </s>
<s snum=35> ilitaqsijumavunga niruaqtauvimmiuqutinnit nanulingmi tavvungaqtittisimammaanga , ammaluttauq qujalijjuarmigama tilijausimagama ministauqataunirmut nutaami gavamami .  </s>
<s snum=36> qaujimagatta maligaliuqtiulluta isulivviqarmata aturvitsavut amma avittuqtaugiaqaqpattutik 26 - nut nunalinnut nunavummi amma amisuullutik tussirautilianguvattut kiinaujaqtaaruasirnirmut .  </s>
<s snum=37> illuliukkannirunnariaqaratta amma pinirsarinngingaarlugit nutannguriariniit amma piusigiariniit .  </s>
<s snum=38> qaujijumatuinnaqpunga tukigijanga piliriamit aturniluutiqarniq asijjisimammangaaq nutaamut maligarmut uvvaluunniit taimailingassainnaqpa .  </s>
<s snum=39> pittautigijjaanngilaq kisiani tukisiajauniqsautiniaqpavut gavamakkut iqqanaijaqtinginnut ajjigiinngittutigut tusaqtijjutikkut .  </s>
<s snum=40> qanuittangittiaraluaqtunga atirnik sivullirnik taigaluaruvinga , ataatama atinga anaruangummat .  </s>
<s snum=41> qikiqtaalummuarasukluni kivallitigut turaakautigijuqtaqanngilagut .  </s>
<s snum=42> tamanna tamainnut kiinaujanuarniaqpaa uvvaluunniit utiqtitauniaqpat nunalinnut pivigijaulauqtunut ?  </s>
<s snum=43> tamanna aaqqigiariaqaqturijara upinnarani qaujimajakka uqalimagunnatsiarningit , uqausirijakka nunaqqatikka .  </s>
<s snum=44> tuksiraummik titiraqulauqpakka ikajuqtuijjutimillu titiqqataarlutit nunalinnit , taimannaummat kiuraaniksimavara apiqqutilu piliriarivavut .  </s>
<s snum=45> maligaliuqtitigut angiqsimanngilagut piqataulaurnatalu piliriamik tamatuminnga kiinaujaillu unikkaanginnik , angiqatigiigutimik takutittijuqalauqqaaqtinnagu akiliiqujinngilanga tamatuminnga ammalu maligaliuqtiit suqquimaqattautilaunnginittinnit kisuulaurmangaata aulanirmut akiliutinit sivunittinniilirutit paippaatigut qimirrujumaniaqpunga tamatuminnga sivunittinni katimalirmigutta .  </s>
<s snum=46> avittuqsimajut apirijauniaqput katimajiralaaqaqtillugit tamainnut taikanilu atangirniqsamik kiujunnaniaqtunga tamatuminnga .  </s>
<s snum=47> pilirijariaqaqquuqtugut nanisiqulluta kaanturaaktinit suuqaimma aturniqsauniaratta ungasiktumut tiurituariami gavamakkut kaanturaaruttigu .  </s>
<s snum=48> maligaliuqtituinnait niriunniqattiaqput angijumik piujumillu atuutiqarniariaksaq tavani gavamakkunni .  </s>
<s snum=49> tunisijaurataaqsimallutalu tuksirautimik tigusinirmik qikiqtaalummi imminiiqtulirinirmut pinasuagarnik .  </s>
<s snum=50> tamakkua isumaaluutit naksalauqpakka , titiraqsimallunga avittuqsimajunut sivumuaqtaullunilu aanniaqtulirinirmut katimajinut qimirrujauniksamut luuttaaq igluksanganut iglulingmuaqtaujunnaqullugu .  </s>
<s snum=51> sanikiluap maijanga katimajingillu isumaalulauqput tamatuminnga ilinnianirmik nuqqatittiniarutta nuttirlugulu qamaniqtuarmut aullatittigunnajjaannginatta ilinniaqtiqutittinnit taavunga .  </s>
<s snum=52> tukisimagiakannilaaraluartunga qanuilaanitingnu pinasuarusiulaaqtumi , tungaagut katimaniup ilagilugi pivallianinginungajunu kuapuriisa kiggaqtuijingini .  </s>
<s snum=53> utiqtitauqullugit nalliat ittarnisait nunavut naammattunit tuqquqsiviqariaqaqput tamakkununnga .  </s>
<s snum=54> pigiakkanirnialirmigatta maligaliuqtilu iqaluttuuttiarmik , unikkaarumaviit kiinaujaqturutiksamut ammalu piviqarniarmangaatta pigiarutinit uqausiksanit .  </s>
<s snum=55> kisianili nalunaiqtaujarialik gavamatuqakkut kiinaujaqaqtittiningat aqqutinganik kiinaujaqaqtittiniummat angijuutinit .  </s>
<s snum=56> suqquimavunga ittuqsiutiksamut kiinaujaqarvik , ittuqsiutiksait akiliqtauraanikpata amiakkuqarajarmata $ 9 milianit , utirviksautaullutit tamainnu kiinaujaqarvingmut .  </s>
<s snum=57> uqaqtii , piviqarvigijumavara tamanna uqarumallunga utiqtittijariaqarnitinnit ittarnisaqutittinnit nunavumut .  </s>
<s snum=58> tunisilauqpaanga uuminga uasukuamik atuqattaniaqtarnit maligaliurvingmi , pilirisimanirnut miqqulirinirmut .  </s>
<s snum=59> atinga uqausirijjaanngita ullumi kisianili ippigiqatiqarninnik uqarumavunga taiksuminnga pirruluaqijumut qimattaujunut niriuppungalu ilaiqtut ikajuqtauniaqtut .  </s>
<s snum=60> maligaliuqtit quviasulaunngilat suqquimanaqtuqannginninganik qanuq aaqqittaujut pijaulaurninginnit .  </s>
<s snum=61> kamagijaqarivuttauq pivalliajaunirmik qaujisaqattanirmillu kiinaujaqturutiksamik avittuqsimajunut .  </s>
<s snum=62> ii , maligaliuqtiulluta maligaliuqtituinnaujutigulluunniit piviqarniqsaujumavugut piqjuanut gavamakkut aaqqiivvigilaunnginninnit .  </s>
<s snum=63> asingit nunaligjuangujut silarjuarmi aksuruqtillugit namminiq sungiutinasugiamik , qanuittuqagajuttukkut inutuinnarnut , uvagut isumagijunnaqpugut tunijauvijjuaqsimanittinnik .  </s>
<s snum=64> iksivautaaq , quviattummariuvunga tusarianga ilanginnit uqausiuqattaqtut amma kiujjutiuqattaqtut tusaqattaqtakka maannamut piluaqtumi tamanna maligaq sivulliqpaangummat taimaittunit maligarnit kanatami .  </s>
<s snum=65> inuit attuatiarngata avatiujumut amma ajjigiingitunut arraagumi qanuinniujunut amma saqqitunut ukiukkun amma upingaakkun .  </s>
<s snum=66> ikajurumavavut saglimiut qanulimaaq ikajurunnaqtatigut taqqini qaijunit .  </s>
<s snum=67> nalunaiqsijariaqaqpugut nalliat titirarviit nuttiqtaujut asianut pilirijunnarniaraluarmangaata gavamaup iluani ammalu tusarvigijumaniarlutit qamaniqtuarmuaqsimanittinni .  </s>
<s snum=68> avittuqsimajuvut tiliuqtausimavut pisimattijiuqullugit inuit iliqqusingannik ittarnisanginnillu .  </s>
<s snum=69> nunavut ingirragiarnialiqtillugu angijummarimmik pijatsaqalangavusi .  </s>
<s snum=70> qaujimajuinnauvugut gavamatuqakkut qaujimajiqutiqalaurmata qulliqpaanit , tusarumatuinnaqtungali tamatuminnga qaujimalaurmangaata , qanuq tikiutititaulaurmangaaq tikittanginnut .  </s>
<s snum=71> kiinaujalirijiga taatsumanngat kiutinniarakku .  </s>
<s snum=72> inuqutivut pijunnautiqaqput taimannak inuusiqainnariaksaq puijiniarlutillu makimajjutiksanginnut .  </s>
<s snum=73> apirijariiqqauvunga niruarumammangaatti pigiaqtitaujumik , kisianili ukaliup uqausingit tungaanut kiujumavit apiqqutinganut uqausinganut ?  </s>
<s snum=74> nalunaiqsijumatuinnaqtunga nutaangullusi maligaliuqtiullusi taisijariaqaratti ippigiqatigijumajattinnit .  </s>
<s snum=75> pigiaqtitsivunga , aippiqtaulluni katimajimut qikiqtaaluup nigianut , nunavuup maligaliurvingata maligangit angiqtauqullugit .  </s>
<s snum=76> qulanngitsiaqtunga aaqqigutitsanik nanisiniarnissinnik qiniqtassinnik .  </s>
<s snum=77> kisianili ministamik tusarumagatta sunaummangaaq piliriaksanga ministauvvinganni .  </s>
<s snum=78> ammalu , tavvani pinasuarusiup nuqqangaarniriniaqtatinni niruaqtauvimmiuqatikka ilangit iqalliaqattautiniqarniarmata uqautijumallugillu sivumuarniqattiaqullugit tamarmillu attanaqtusiujjaanngittut quviasunniqaqtillugit .  </s>
<s snum=79> atausiq uuttuutigilugu uvanga nunalinganiittuq , qaujimajunga taavaniikutaannikuugavit ammalu nalugalakkaluaqtunga qanutigikkanniq qangaluunniit nuqqavigajarmangaaq .  </s>
<s snum=80> taimannaummat amisuuvut isumaaluutit aulattittariaqaqtavut maannaujuq , tamannalu sivulliujjaulluni avittuqsimajulimaani .  </s>
<s snum=81> utirlunga asianut apiqqutaujumut , uqaqqaugavit akiliiluarniq kamisanaulaukaktulirijikkunni akiliksauniarmat kajusigiaqtaujumik ilanngairutauniaqtuni piqutinut piniaqtatinnit nunattiap gavamanganik .  </s>
<s snum=82> nillirviqarumallunga tavvali ippigiqatiqarnitinnit jaani aupaluktaup qatanngutinginnut uinga it puutan pirruluaqilluni sivataarvingmi inuujunniilaurmat .  </s>
<s snum=83> iqqanaijaqtivut tiliurisimavavut unikkaamik parnaijaqullugit qaujigiarnirmillu qimirruniarillutigulu taqqiulaaqtumi ulluunnik marruunnik 29mi 30milu .  </s>
<s snum=84> immaqa piunirsaugajartuq angunasuktiit umianginnut qaujimallungalu ilangit nunaliit niuraiviqangittut taikkua ikpigittiarniaqpavut nunaliit .  </s>
<s snum=85> uqarniaqqaugaluarama uattiasaaq kisianili amisunit uimmajausimagatta maligaliuqtiulisaarnitinnut ammalu tusaajaunngittuujumalauqtunga uqarumajarnut .  </s>
<s snum=86> tavvuuna akaunngiliuqtittivuq nalunaiqtaulaunnginningani maligaliuqtinut suqquimajariaqarmata kisumut akilirialiit pijaulaurmangaata .  </s>
<s snum=87> nutaamik ikumaliurutitaarniaqsimagaluaratta sannginiqsamik , tusalisaaqtugulu titiqqaup naliqqanganik pisimananga .  </s>
<s snum=88> kisunit parnautiqaqpit atuqtaukkaniqtittinirmik ikajuusianit iqqanaijaqtitta pilauqsimajanginnit .  </s>
<s snum=89> piunngilaq uqatuinnarianga qaujimanninngigianga , qanuittuqarniqpat taiknalu qaujijaunniqpat piliriamit aturniluutiqarninga .  </s>
<s snum=90> taimali ministaullutit , angirunnaqpit pigiarutiksaugajaqtunik nutaamut piliriamut ammalu pijitsirutaujunut ilipsi pilirivinganut angirutaugajaqtumut tamaksumunga pijaujariaqaqtumut .  </s>
<s snum=91> katimajiralaat atuliqtauqujimmijut avittuqsimajut pilirinasuqullugit nalunanngittunit kiinaujaqturutiksanit tusaqtittijjutiqaqullugit innarnut inulimaanullu .  </s>
<s snum=92> taanna anautaq tunijauniaqtuq katimavingmut takuksautitsiniqaqtuq pijunnautinik ajunginnirijanganillu niruaqtausimajut maligaliurviup .  </s>
<s snum=93> apiqqutinganut maligaliuqtiup , taikkua tukisigiarutiksaujut atuinnaringinnakkit amma angajuqqautikka tamaksumunga kiujjutiksaujumut qiniqtut maligaliuqtiup apiqqutinganut .  </s>
<s snum=94> pattatturumavakka tamarmik angajuqqaarijaujut iglumiuqatigijaujullu aksurulauqtut ikajuqtutit tamakkuninnga isulittijunit .  </s>
<s snum=95> quviappunga pivissaqaqtitaunirnut ullumi maligaliurvimmut nalunaiqsigianga katimajiralaatta unikkaalianginnit qimirrunirmut maligassaq 9 - mit - asijjiinirmut atirnik maligaq , 2001 .  </s>
<s snum=96> immaqa ilinniaqtitaujunnaqqata piugajaqtuugaluaq  </s>
<s snum=97> minarisimajavuk tamannuk isumaaluutingit gavamangata nunavuup taikunga katimajiralaanginnut amma taikkua katimajiralaangit tusaajut tamatuminga isumaaluutinik amma pilirimmijut piusinasuarsugu piunirsarurasuarsugulu sivuniuniartumut .  </s>
<s snum=98> katimajiralaat unikkaaliraangata uqallaqatigiiluaqattanngillusi upigilugit maligaliuqtit unikkaaliraangata , tusaaqataulusi .  </s>
<s snum=99> ilinniavitta titiqtugangit sanajauniksangalu pituinnaulauraluarmata sanirajarmut , kisianili arraagutta akitujuqsiutinginnut takujunnannginakku .  </s>
