<s snum=25> Our hunters , our people , were recognized and applauded for the sustainable and humane way we conduct our seal hunt .  </s>
<s snum=26> In the beginning the goals of the Government were that the Government would be open and that there would be a close working relationship , that is what we are trying to establish right now , that is what we agreed to in the beginning .  </s>
<s snum=27> I would like to remind everyone that you will have the opportunity to address these concerns during the committee of the whole .  </s>
<s snum=28> We also recognize that the capacity of departments to translate all materials into Inuktitut is , at present , limited .  </s>
<s snum=29> Mr. Speaker I really enjoyed myself last week visiting Igloolik with the member for Amittuq .  </s>
<s snum=30> The community had heard that this arena was going to be built this year , but now we are hearing something else .  </s>
<s snum=31> Mr. Speaker , I believe that we all know and are proud of the people because of course the Hamlets and ourselves were elected by the people out there .  </s>
<s snum=32> Yes , I am sorry , he asked me this question a few days ago and I made a mistake when I was responding to that .  </s>
<s snum=33> I would also like to say thank you on behalf of my wife Miriam and my children and my twins , because the Coral Harbour people have been very receptive to us for the past thirteen years that we have been living there .  </s>
<s snum=34> Are you going to be looking at this concern from Pelly Bay and will there be a gym built this year ?  </s>
<s snum=35> I would like to recognize my constituency of Nanulik who have put me into this House , and I am also very thankful that I have been appointed as a Minister of the new Government .  </s>
<s snum=36> As Members of the Legislative Assembly , we know that we have limited resources and they have to be divided up to the 26 communities of Nunavut and there are lots of applicants out there who apply for funding .  </s>
<s snum=37> We have to be able to make more houses and then take a little less for improvements and renovations .  </s>
<s snum=38> I am just wondering if the definition of conflict of interest itself has changed within this new legislation or has it remained the same .  </s>
<s snum=39> It is going to take time , however we are going to have it more understood by the Government personnel through various means of communication .  </s>
<s snum=40> I don't mind at all if you refer to me by my first name , my dad's name is Anawak .  </s>
<s snum=41> When you are trying to go to the Baffin Region from Keewatin , we have no mode of transportation directly .  </s>
<s snum=42> Will this money go back into general revenue or does it go back to the communities where we generated it from ?  </s>
<s snum=43> I feel that this has to be improved because I know that they are very articulate , I am talking about my home community .  </s>
<s snum=44> I asked them to write a proposal and get a letter of support from the community , so I have already responded to that and we are working on that question .  </s>
<s snum=45> We have not agreed as MLA's , and we were not involved at all in this endeavour and in respect to the financial details , before there is an agreement shown I would not want to make a payment on this and as MLA's and unless we understand each other as to what the operational costs were when they are in front of us on paper , I would want to review this again in our future meetings .  </s>
<s snum=46> The different departments will be asked questions during committee of the whole and during that time I can make a more detailed response to that question .  </s>
<s snum=47> I believe that we will have to work hard to find contractors because of course we will be spending more in the long run if we contract the territorial government .  </s>
<s snum=48> Regular members look forward to making a strong , positive contribution to this government .  </s>
<s snum=49> We have also just recently been presented with a proposal for taking all of the North Baffin suicide workshops .  </s>
<s snum=50> I took those concerns back , I've written a letter to the department which was forwarded on to the Health Board for review to look at suitable accommodations for the doctor so we can put the doctor in place in Igloolik .  </s>
<s snum=51> The Mayor of Sanikiluaq and the Hamlet Councillors were concerned that if we are going to stop this training program and move it to Baker Lake , we won't be able to send any of our trainees over there .  </s>
<s snum=52> I will have more of a sense of where we are going next week , after the meeting with the Development Corporation representatives .  </s>
<s snum=53> In order to bring back any artifacts , Nunavut has to have sufficient storage space to locate these items .  </s>
<s snum=54> We will now resume our meeting and the M . L . A . from Cambridge Bay , do you want to address the budget and then we will have an opportunity to have opening comments .  </s>
<s snum=55> However , it should be pointed out that federal investment in bandwidth is an investment in infrastructure .  </s>
<s snum=56> It is my understanding that the pension fund , after all of the pensions were paid out , there would be approximately 9 million dollars left over , that was going to go back into the general funds .  </s>
<s snum=57> Mr. Speaker , I would like to take this opportunity to speak on the need to return our artifacts to Nunavut .  </s>
<s snum=58> They presented me with this vest to wear at the Legislature , because of the work that I have been doing for the fur industry .  </s>
<s snum=59> I will not be announcing the name today but I would like to express my sympathy to the survivors of that accident victim and I hope that the family will receive support .  </s>
<s snum=60> Members were disappointed at the lack of clarity provided as to how some decisions were arrived at .  </s>
<s snum=61> It is also responsible for development and monitoring of the budget of the Department .  </s>
<s snum=62> Yes , as members of the Legislative Assembly , or the regular members , we would like to get more opportunity to give input on important issues before the Government decides on them .  </s>
<s snum=63> As other nations around the world struggle to define themselves , often with great human cost , we count ourselves very lucky .  </s>
<s snum=64> Mr. Chairman , I am really glad to hear some of the comments and answers that I have heard so far especially on the idea that this legislation is at the leading edge of this type of legislation in Canada .  </s>
<s snum=65> The Inuit are very closely linked to the environment and to the different seasons and it's results in the winter and in the spring .  </s>
<s snum=66> We would like to help the residents of Coral Harbour as much as we can in the coming months .  </s>
<s snum=67> We have to make sure that any offices that relocate elsewhere will be able to work within the government and we will be looking for your input during the retreat in Baker Lake .  </s>
<s snum=68> My Department has been tasked as the guardian of our Inuit Culture and Heritage .  </s>
<s snum=69> As Nunavut takes flight you are dealing with immense challenges .  </s>
<s snum=70> We all know that the Federal Government had federal advisors right at the highest levels , I was wondering how , if they were aware of this , how they let it get to the level it was .  </s>
<s snum=71> I will get my finance person to answer that question .  </s>
<s snum=72> Our people have the right to continue this way of life , and to hunt seal for their livelihoods .  </s>
<s snum=73> I had already asked if you wanted to vote on the motion , but in regards to Okalik's comment would you like to reply to his question or comment ?  </s>
<s snum=74> I would just like to clarify that as you are new members , we have to provide a name for those people who we are paying sympathy to .  </s>
<s snum=75> I move , seconded by the Honourable Member for South Baffin , that the Rules of the Legislative Assembly of Nunavut be adopted .  </s>
<s snum=76> I have no doubt that you will find the solutions that you seek .  </s>
<s snum=77> But we would also like to hear from the minister himself as to what his mandate is in his department .  </s>
<s snum=78> Also , just this past weekend some of my constituents will be having a fishing derby and I would like to pass on to them that they have good luck and that everybody will be safe during these celebrations .  </s>
<s snum=79> One example is in my community , I know you've been there for quite some time and I'm not sure , how much more time or when he's going to retire .  </s>
<s snum=80> So , there's a lot of issues that we have trying to get operational right now , that has been the priority of all of the departments .  </s>
<s snum=81> Going back to another question , you mentioned that the over - expenditure from the OIC office would be a liability that's been carried forward that's going to be offset against assets that we're getting from the GNWT .  </s>
<s snum=82> I would like to take this opportunity to express our sympathy to the family of Jane Aupaluktuk . Her husband Ed Burton had an accident on Saturday and passed away .  </s>
<s snum=83> We have directed our staff to prepare a report and an evaluation and we are going to look at that next month for two days on the 29th and 30th .  </s>
<s snum=84> Perhaps it would be better for the hunters' boats and I know that some communities do not have facilities and we will be sensitive to those communities .  </s>
<s snum=85> I was going to say this earlier , but so much has been happening that resulted from our being a new Legislature , and I did not want anybody to miss what I have to say .  </s>
<s snum=86> That way it is creating a problem unless it is clarified both to the MLAs because they have to understand for what the payables have been incurred .  </s>
<s snum=87> We are supposed to get a new plant with better capacity , I have just heard about it and don't have a copy of the letter .  </s>
<s snum=88> What are your plans for re - implementing the benefits packages our employees use to have .  </s>
<s snum=89> It is not good enough to say that he or she didn't know , if something were to happen and that individual were found to be in a conflict of interest situation .  </s>
<s snum=90> Can you , as the minister , commit to starting up a new program and services for your department to address that need .  </s>
<s snum=91> The Committee also recommends that the Department make an effort to provide clear budget information to elders and the public .  </s>
<s snum=92> The mace , which will shortly be presented to the House , is itself a reflection of the rights and authority of a democratically elected Assembly .  </s>
<s snum=93> For the question from the member , I don't have the information in front of me and my officials are looking into the answer to the member's question .  </s>
<s snum=94> I would like to praise both the parents and families who worked hard in assisting these graduates .  </s>
<s snum=95> I am very pleased to have the opportunity today to provide the House with an overview of our Committee's Report on the Review of Bill 9 - Change of Name Act , 2001 .  </s>
<s snum=96> Perhaps if they could be taught it would be ideal  </s>
<s snum=97> We both brought the concerns of the Government of Nunavut to that committee and the committee is listening to those concerns and is working also to improve and make things better in the future .  </s>
<s snum=98> When the Committees are reporting please hold down your chat , in respect to the members , when they are reporting , please listen .  </s>
<s snum=99> The blueprints and design of our school was all ready for Hall Beach , but I do not see it in this year's capital projects .  </s>
